# Generated by Django 3.1.4 on 2021-04-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210418_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='qualifiation',
            new_name='qualification',
        ),
    ]
